apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: domserver
  namespace: domjudge
spec:
  selector:
    app: domserver
  replicas: 1
  template:
    metadata:
      labels:
        app: domserver
    spec:
      containers:
        - env:
          - name: CONTAINER_TIMEZONE
            value: Asia/Taipei
          - name: MYSQL_DATABASE
            value: [desired value]
          - name: MYSQL_HOST
            value: 172.30.33.6
          - name: MYSQL_PASSWORD
            value: [desired value]
          - name: MYSQL_ROOT_PASSWORD
            value: [desired value]
          - name: MYSQL_USER
            value: [desired value]
          image: ' '
          name: domserver
          ports:
          - containerPort: 80
            protocol: TCP
            name: domserver
          securityContext:
            privileged: true
      nodeName: [desired node's name]
      restartPolicy: Always
      serviceAccountName: privrun
      serviceAccount: privrun
  test: false
  triggers:
    - type: "ConfigChange"
    - type: "ImageChange"
      imageChangeParams:
        automatic: true
        containerNames:
          - domserver
        from:
          kind: "ImageStreamTag"
          name: "domserver:latest"
  strategy:
    type: "Recreate"
  paused: false
  revisionHistoryLimit: 2
  minReadySeconds: 0
