apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: judge-with-init
  namespace: domjudge
spec:
  selector:
    app: judge
  replicas: 1
  template:
    metadata:
      labels:
        app: judge
    spec:
      containers:
        - env:
          - name: CONTAINER_TIMEZONE
            value: Asia/Taipei
          - name: DAEMON_ID
            value: '0'
          - name: DOMSERVER_BASEURL
            value: http://172.30.222.22:22222/
          - name: JUDGEDAEMON_PASSWORD
            value: [desired password for judges]
          - name: JUDGEDAEMON_USERNAME
            value: judgehost
          image: ' '
          name: judge-0
          resources:
              requests:
                  cpu: 1
                  memory: [desired memory space, e.g. 2048Mi]
              limits:
                  cpu: 1
                  memory: [memory limit, e.g. 2048Mi]
          securityContext:
            privileged: true
        - env:
          - name: CONTAINER_TIMEZONE
            value: Asia/Taipei
          - name: DAEMON_ID
            value: '1'
          - name: DOMSERVER_BASEURL
            value: http://172.30.222.22:22222/
          - name: JUDGEDAEMON_PASSWORD
            value: [desired password for judges]
          - name: JUDGEDAEMON_USERNAME
            value: judgehost
          image: ' '
          name: judge-1
          resources:
              requests:
                  cpu: 1
                  memory: [desired memory space, e.g. 2048Mi]
              limits:
                  cpu: 1
                  memory: [memory limit, e.g. 2048Mi]
          securityContext:
            privileged: true
        - env:
          - name: CONTAINER_TIMEZONE
            value: Asia/Taipei
          - name: DAEMON_ID
            value: '2'
          - name: DOMSERVER_BASEURL
            value: http://172.30.222.22:22222/
          - name: JUDGEDAEMON_PASSWORD
            value: [desired password for judges]
          - name: JUDGEDAEMON_USERNAME
            value: judgehost
          image: ' '
          name: judge-2
          resources:
              requests:
                  cpu: 1
                  memory: [desired memory space, e.g. 2048Mi]
              limits:
                  cpu: 1
                  memory: [memory limit, e.g. 2048Mi]
          securityContext:
            privileged: true
      restartPolicy: Always
      serviceAccountName: privrun
      serviceAccount: privrun
  test: false
  triggers:
    - type: "ConfigChange"
    - type: "ImageChange"
      imageChangeParams:
        automatic: true
        containerNames:
          - judge-0
          - judge-1
          - judge-2
        from:
          kind: "ImageStreamTag"
          name: "judge-with-init:latest"
  strategy:
    type: "Recreate"
  paused: false
  revisionHistoryLimit: 2
  minReadySeconds: 0
