apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: mariadb
  namespace: domjudge
spec:
  selector:
    app: mariadb
  replicas: 1
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - args:
          - --max-connections=1000
          env:
          - name: MYSQL_ROOT_PASSWORD
            value: [desired value]
          - name: MYSQL_DATABASE
            value: [desired value]
          - name: MYSQL_USER
            value: [desired value]
          - name: MYSQL_PASSWORD
            value: [desired value]
          image: ' '
          name: mariadb
          ports:
          - containerPort: 3306
            protocol: TCP
            name: mariadb
          securityContext:
            privileged: true
          volumeMounts:
            - name: dbval
              mountPath: /var/lib/mysql
      nodeName: [desired node's name]
      volumes:
        - name: dbval
          hostPath:
            path: [desired path on the desired node]
      restartPolicy: Always
      serviceAccountName: privrun
      serviceAccount: privrun
  test: false
  triggers:
    - type: "ConfigChange"
    - type: "ImageChange"
      imageChangeParams:
        automatic: true
        containerNames:
          - mariadb
        from:
          kind: "ImageStreamTag"
          name: "mariadb:latest"
  strategy:
    type: "Rolling"
  paused: false
  revisionHistoryLimit: 2
  minReadySeconds: 0
