apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: judge-with-init-6.0.3
  namespace: domjudge
spec:
  output:
    to:
      kind: ImageStreamTag
      name: "judge-with-init:6.0.3"
  source:
    dockerfile: |-
      FROM domjudge/judgehost:yee
      RUN apt update
      RUN apt install dumb-init
      ENTRYPOINT ["/usr/bin/dumb-init", "--"]
      CMD ["/scripts/start.sh"]
  strategy:
    dockerStrategy:
      from:
        kind: "ImageStreamTag"
        name: "judgehost:6.0.3"
  triggers:
    - type: "ConfigChange"
    - type: ImageChange
      imageChange: {}
