apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: judge-with-init-core-unbound
  namespace: domjudge
spec:
  output:
    to:
      kind: ImageStream
      name: "judge-with-init-core-unbound"
  source:
    dockerfile: |-
      FROM domjudge/judgehost:yee
      RUN apt update
      RUN apt install dumb-init
      RUN sed -i 's/CPUSET_OPT="-P $CPUSET"//g' /opt/domjudge/judgehost/lib/judge/testcase_run.sh
      ENTRYPOINT ["/usr/bin/dumb-init", "--"]
      CMD ["/scripts/start.sh"]
  strategy:
    dockerStrategy:
      from:
        kind: "ImageStream"
        name: "judgehost"
  triggers:
    - type: "ConfigChange"
    - type: ImageChange
      imageChange: {}
