apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: domjudge
spec:
  selector:
    app: mariadb
  ports:
    - name: "3306"
      protocol: TCP
      port: 3306
      targetPort: 3306
  clusterIP: 172.30.33.6
  type: ClusterIP

